steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/kubassignment-441102/kub-assignment/kubcontainer2",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/kubassignment-441102/kub-assignment/kubcontainer2",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials kub-assignment-cluster --region us-central1
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: Deployment
    args:
      [
        "run",
        "--filename=deployment-kubcontainer2.yaml",
        "--image=us-central1-docker.pkg.dev/kubassignment-441102/kub-assignment/kubcontainer2",
        "--location=us-central1",
        "--cluster=kub-assignment-cluster",
      ]
images:
  - "us-central1-docker.pkg.dev/kubassignment-441102/kub-assignment/kubcontainer2"

options:
  logging: CLOUD_LOGGING_ONLY
