apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-pod
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      name: container2
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-central1-docker.pkg.dev/kubassignment-441102/kub-assignment/kubcontainer2:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /file_Dir
          ports:
            - containerPort: 7000
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-pod
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
